executable = /afs/desy.de/user/d/dudarboh/ILCSoft/TOFAnalysis/job/2f_Z_hadronic.sh
arguments = $(file) $(ProcId)

initialdir = /nfs/dust/ilc/user/dudarboh/job_files/jobs
should_transfer_files = NO

log = ../log/$(ProcId).log
output = ../out/$(ProcId).out
error = ../err/$(ProcId).err

request_cpus = 1
request_memory = 500MB
request_disk = 1500MB
Requirements = OpSysAndVer == "CentOS7"

queue file from /afs/desy.de/user/d/dudarboh/ILCSoft/TOFAnalysis/job/2f_Z_test.txt
