executable = /afs/desy.de/user/d/dudarboh/ILCSoft/TOFAnalysis/job/calib_kaons.sh
arguments = $(slcio_file) $(ProcId)

initialdir = /nfs/dust/ilc/user/dudarboh/job_files/jobs
should_transfer_files = IF_NEEDED
when_to_transfer_output = ON_EXIT

log = ../log/$(ProcId).log
output = ../out/$(ProcId).out
error = ../err/$(ProcId).err

queue slcio_file from /afs/desy.de/user/d/dudarboh/ILCSoft/TOFAnalysis/job/calib_kaons.txt
